### PR TITLE
Ansible Collection Creation

### PR DESCRIPTION
**Pull request by darkdecoy**
- Reorganize into an ansible collection
- Fixes errors and warnings from ansible-lint and ansible-test
- Add bash script for generating certificates into the collection rather than downloading it at run time
- Fix issue with script when the working directory path has a space in it
- Added missing dependency for Almalinux 9
- Updated/Created documentation for roles, playbooks and collections
- Fixed issue with having to set query for windows log format eventchannel

### CODE REVIEW

**Comment by teddytpc1** [comment]
Hi @atcommander.
First of all, thanks for your contribution. 
Unfortunately, the PR is too big to review and includes major changes that would be better to analyze separately. So, I will ask you to:
- Update your `4.3` branch with the latest changes.
- Create a PR for each item so we can review them one by one.

**Comment by nlamirault** [comment]
hi, any news on this feature ?

**Comment by zollo** [comment]
Bumping this, we cannot consume the Wazuh content without a proper collection structure.

**Comment by goetzk** [comment]
> Bumping this, we cannot consume the Wazuh content without a proper collection structure.

As best I can tell Wazuh don't care about Ansible users or improving their situation. Small changes #929 , #930, #931 have been ignored since September last year and - based on my looking at the commit history - there has been virtually no community supplied changes being merged. No changes of substance are happening in the repository.

I assume there are lots of people bodging their way by importing playbooks, forking the repository, and wrapping it up in other ways.

I'm thinking about changing platform, because management is an important part of tooling like this.

**Comment by noonedeadpunk** [comment]
I wanna +1 to this effort, as in 2024 having just playbooks and roles without them being installable as a collection is quite useless and against best practices.

**Comment by ct-jby** [comment]
Any news?

I don't understand why this PR was never merged.

it's unacceptable in 2024 to have to tinker to deploy and maintain a tool like Wazuh.

Several people have tried to improve and provide everything needed for an ansible collection, but have hit a brick wall.

I think that's a real shame.

**Comment by spatterIight** [comment]
With Collection:
  1. Install collection
  2. Use the role in a playbook

Without collection:
1. Clone this repo
2. Create a new private repo called "ansible-role-wazuh"
3. Copy the contents of roles/wazuh into the new repo "ansible-role-wazuh"
4. Install the new private role
5. Use the role in a playbook
6. Periodically manually update the contents of your private role repo with upstream

I hope this helps explain how important the functionality of being installable as a collection is.

**Pull request closed without merging**
