### PR TITLE
Template API configuration

### PR DESCRIPTION
**Pull request by colbyprior**
Hi,

I wanted to add the ability configure the API so that I can force it to work over HTTPS.

I also added the ability to set wazuh_agent_config.name when registering an agent instead of using hostname for instances I deploy in AWS. Let me know if you would like this as a separate pull request.

Please let me know if there is anything else I should add to the template for the API as I am quite new to Wazuh.

Thanks, Colby

### CODE REVIEW

**Comment by cadoming** [comment]
Hi @colbyprior,

Thank you very much for your work, for future occasions if we would prefer you to do two separate PRs.  

Regarding the API configuration part, I created the PR #80  by adding your proposed changes but adapting them to the structure of the 3.7 branch.

Regarding the part of the host name modification I have some doubts, if I'm not wrong you have not declared the variable `wazuh_agent_config.name` that you use. If I declare it still gives me the following error.

Declaration of the variable in `defaults/main.yml`:
image

Error:
image

**Comment by colbyprior** [comment]
Hi @cadoming,

Thanks so much for looking at this! Sorry my local branch I was working in had an alteration of this and I didn't test this properly.

I fixed this with a statement to set the flag if `wazuh_agent_config.name` is defined. The default of the fag is set to hostname if not defined anyway, not sure why I didn't set it this way from the beginning.

**Comment by cadoming** [comment]
Hi @colbyprior, 

We have some doubts about the changes you propouse to add the ability to set wazuh_agent_config.name. We believe that with the code you propose only takes into account the installation of a few amount of agent, if more than one agent were installed in the same deployment we would be giving the same name to all agents (the name we define with wazuh_agent_config.name). Ansible has the ability to install many agents at the same time and we also have to consider that possibility.

 Please, tell us if we are making a mistake with these conclusions and which solution you will propose in case of the installation of more than one agent at the same time.

Carlos

**Comment by colbyprior** [comment]
Hi Carlos,

I have some servers in an on-premise data centre. For this I would use a single playbook to deploy Wazuh to all servers and not set the wazuh_agent_config.name variable so that the names get populated by the hostname.

As for some Ec2 instances in AWS, they get deployed with hostnames in for format ip-<ip-address>. When I see an even in Wazuh on one of these instances I have to boot the console to find what application that IP address is associated with.

My current solution is that my Ec2 instances get Wazuh deployed as part of their `user-data` config and I set the wazuh_agent_config.name equal to the `Name` tag that I set in AWS. Has someone else had this issue before and overcome it in a more elegant way? I am open to suggestions :slightly_smiling_face:

**Comment by jesuslinares** [comment]
Hi @colbyprior ,

We will continue this discussion here: https://github.com/wazuh/wazuh-ansible/issues/91.

Thanks for your contribution!.

**Pull request closed without merging**
