### PR TITLE
updated wazuh-soc for single node

### PR DESCRIPTION
**Pull request by auasad**

### CODE REVIEW

**Comment by teddytpc1** [comment]
Hi @auasad. 
Most of the changes in the PR seem to be custom changes for your own environment. Those changes are not considered improvements to the repository. Maybe you should create the PR in your own fork.
That being said, this PR will not be considered for merging.
Thanks anyway.

**Comment by auasad** [comment]
Hello Gunzalo, I hope yare doing well. You are right, the changes l made
are specifically related to my environment. I had already forked the repo
and push my branch.
We are actually ELK consultant and now started implementing Wazuh for our
clients seeking SOC or SIEM tools.

**Comment by teddytpc1** [comment]
Glad to hear that. Feel free to open an issue or a thread in the Wazuh Slack Community channel if you need anything.

**Comment by auasad** [comment]
Thanks, please share link to the slack and other chanels.

**Comment by teddytpc1** [comment]
You can join with this link:
https://wazuh.com/community/join-us-on-slack/#thank-you

**Pull request closed without merging**
