### PR TITLE
Improve example playbooks

### PR DESCRIPTION
**Pull request by neonmei**
This PR refreshes example playbooks and config distributed within the playbook directory. It also sports a README and example playbook on how to create a lab environment with docker to play around with these.

### CODE REVIEW

**Comment by sergiogp98** [comment]
Hi team,

When I try to deploy a distributed environment with *wazuh-elasti_stack-dsitributed.yml* I found some issues:

image

I could fix this error by initializing the relative path in **roles.role** var as follows:

```yml
- name: Deploy a single Kibana
  hosts: es-kib01
  roles:
    - role: ../roles/elastic-stack/ansible-kibana
      vars:
        kibana_xpack_security: true
        kibana_node_name: es-kib01
        elasticsearch_network_host: es-node01
        elasticsearch_xpack_security_password: elastic_pass
        wazuh_api_credentials:
          - id: default
            url: https://wz-mgr01
            port: 55000
            username: wazuh
            password: wazuh
```

SG

**Comment by neonmei** [comment]
Hello Sergio!

The error you see is because `ansible-playbook` is being run from the root of the repository instead of the `playbooks` directory.  Generally the implicit rule of the Ansible world is executing `ansible-playbook` from the directory containing the `ansible.cfg` file, so the distributed configuration autoloads. In this case the roles are not being found because the [roles_path] key in the [ansible.cfg file] is not loaded.

Perhaps this could be clarified on the readme so it's more accesible for newcomers :+1: 

Regards.

P.S: That said, I will unassign myself from the issue because I left the company, but feel free to update the PR and reach out if you have any doubts regarding my open PRs or issues.

[roles_path]: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-roles-path

[ansible.cfg file]: https://github.com/wazuh/wazuh-ansible/blob/feature-playbooks-examples/playbooks/ansible.cfg#L6

**Comment by sergiogp98** [comment]
Hi!

I have been testing all the different deployments and I am quite impressed with how easily you can deploy different nodes within different environments. Great job @neonmei . These are the following environment which I have tested:

- [ ] wazuh-elastic_stack-distributed
- [ ] wazuh-all-in-one
- [ ] wazuh-odfe-all-in-one

**wazuh-elastic_stack-distributed**

For this environment, I have used *wazuh-docker-lab.yml* configuration file. It is very useful since the deployment in containers is much faster than virtual machines. I could manage to install correctly:

image

image

**wazuh-all-in-one**

This environment is quite useful when you need only one node. I could manage to install correctly:

image

However, when I tried to access via HTTPS I could not make it. I think it would be a great idea to use an encrypted channel.

**wazuh-odfe-all-in-one**

This environment, as the previous one, creates a single node but with ODFE . 
At the beginning, I could not manage to install correctly since [elasticsearch_network_host](https://github.com/wazuh/wazuh-ansible/blob/a38bb00861bb24e361b4ddd17ff394746e1897aa/playbooks/wazuh-odfe-kibana.yml#L9) of odfe-elastic playbook was not the same as [elasticsearch_network_host](https://github.com/wazuh/wazuh-ansible/blob/a38bb00861bb24e361b4ddd17ff394746e1897aa/playbooks/wazuh-odfe-elastic.yml#L14) variable of odfe-kibana playbook showing the following error:

image

I could fix it by initializing the same value to both variables:

image

SG

**Comment by neonmei** [comment]
Hi, great news! :tada: 

About `wazuh-odfe-all-in-one`, there's a slight difference regarding what `elasticsearch_network_host` means for the elasticsearch and kibana role.

On the kibana role, this variable is used to configure [elasticsearch.hosts], which indicates the address of elasticsearch nodes to run queries against.

On the elasticsearch role it's used to configure [network.host], which is for setting up on which network interface you want to listen for incoming connections (i.e: you might have multiple network interfaces, one being exposed to insecure wan and other on a private network  where you might want to receive connections). In that sense `0.0.0.0` is a way to say "listen on all available interfaces".
So, it won't give you the error you see because it's very permissive (maybe elastic is taking too long to start, some early oom software is kicking in, maybe hitting disk low watermark). In my case I did a playbook run and couldn't reproduce it, so my advise would be deleting the containers, re-deploying on a clean slate and check container logs in case it repeats itself:
    
```
$ docker exec -it es-node01 bash
[root@es-node01 /]# less /var/log/elasticsearch/wazuh.log
```

So, as recommendation for another issue/PR I believe `elasticsearch_network_host` should be renamed on the kibana role to something clearer and re-fitted to [allow receiving an array] (for high availability setups) similarly to wazuh-puppet#317 PR. Regarding the missing elasticsearch-xpack scenario, feel free to add it :+1: 

Regards.


[network.host]: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings

[elasticsearch.hosts]: https://www.elastic.co/guide/en/kibana/current/settings.html

[allow receiving an array]: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#discovering-the-data-type

**Comment by sergiogp98** [comment]
Hi @neonmei ,

The problem raises up when Kibana try to listen to Elasticsearch node ([task](https://github.com/wazuh/wazuh-ansible/blob/a38bb00861bb24e361b4ddd17ff394746e1897aa/roles/opendistro/opendistro-kibana/tasks/main.yml#L87)). I think it can not resolve _es-node01.wazuh.com_ hostname. I could solve it by pointing _es-node01.wazuh.com
_ to _127.0.0.1_ IP address modyfing _/etc/hosts_. Then, I rerun the playbook and everything worked fine. Do you think that might be the problem?

Regards,
SG

**Comment by neonmei** [comment]
`[maintenance]`

closing abandoned PR automatically by script.
feel free to copy the branch and/or rebase if anyone has further interest in proposed changeset.
thank you!

**Pull request closed without merging**
