### PR TITLE
Updated README.md to have self-contained playbook

### PR DESCRIPTION
**Pull request by paulcalabro**
Updated the README.md file to use role parameters instead of CLI args. This keeps it self-contained.
This also ensures you know what variable data was passed to the role at runtime .

### CODE REVIEW

**Comment by paulcalabro** [comment]
p.s. the intent is just to reduce the amount of files needed to get this working OTB.

**Comment by jm404** [comment]
Hi @paulcalabro ,

Having different examples of playbooks configuration in the README is a great idea. As the issue is old, some updates are required to adapt the playbooks to the new variables

**Comment by manuasir** [comment]
Hi @paulcalabro ,

This content will be transferred to our Documentation repository. Don't hesitate to collaborate here again.

Thank you

**Comment by paulcalabro** [comment]
Thanks @jm404 @manuasir ! I've switched to a different team so have been a little less involved in the project, but will most likely be making more contributions in the future as time permits.

**Pull request closed without merging**
