### PR TITLE
use ansible_facts to reference facts

### PR DESCRIPTION
**Pull request by GregWhiteyBialas**
By default, Ansible injects a variable for every fact, prefixed with
ansible_. This can result in a large number of variables for each host,
which at scale can incur a performance penalty. Ansible provides a
configuration option [0] that can be set to False to prevent this
injection of facts. In this case, facts should be referenced via
ansible_facts.<fact>.

This change updates all references to Ansible facts from using
individual fact variables to using the items in the
ansible_facts dictionary. This allows users to disable fact variable
injection in their Ansible configuration, which may provide some
performance improvement.

[0] https://docs.ansible.com/ansible/latest/reference_appendices/config.html#inject-facts-as-vars

### CODE REVIEW

**Comment by teddytpc1** [comment]
Hi @GregWhiteyBialas.
The PR should contain only this [commit](https://github.com/wazuh/wazuh-ansible/pull/893/commits/afeb107b262fce2be61f8cfecea64590ee1da973). It seems that you have `master` changes in your `4.4` branch.

**Review by vcerenu — DISMISSED** [review]

**Review by jnasselle — CHANGES_REQUESTED** [review]
Hi @GregWhiteyBialas,

Gj here! thanks for contributing to Wazuh!

They're still a file that need to be modified in order to be 100% compatible

https://github.com/wazuh/wazuh-ansible/blob/4.4/.github/playbooks/single-wazuh.yml

**Comment by GregWhiteyBialas** [comment]
Oh, sorry for this! I didn't expect anything in there. God lesson for the future. Fixed!

**Review by jnasselle — CHANGES_REQUESTED** [review]
Hi @GregWhiteyBialas ,

Sorry about requesting changes again, but after a deeper search, I found other variables that should be changed

https://github.com/wazuh/wazuh-ansible/blob/4.4/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L73

- `ansible_hostname` to  `ansible_facts.hostname`
- `ansible_default_ipv4.address` to `ansible_facts.default_ipv4.address`

Thanks again!

**Comment by GregWhiteyBialas** [comment]
Hi @jnasselle 
It is I who should say sorry :) 
I have made requested changes, I hope it s all good now.

**Comment by GregWhiteyBialas** [comment]
I have squashed commits in this PR to, avoid clutter in history.

**Review by teddytpc1 — APPROVED** [review]

**Review by jnasselle — APPROVED** [review]
LGTM

**Comment by teddytpc1** [comment]
Hi @GregWhiteyBialas.
Thanks for the changes. This PR will be merged after the `4.4.0` release.

**Comment by teddytpc1** [comment]
Hi @GregWhiteyBialas.
Thanks for the changes. This PR will be merged after the `4.4.0` release.

**Comment by teddytpc1** [comment]
Hi @GregWhiteyBialas.
Thanks for the changes. This PR will be merged after the `4.4.0` release.

**Comment by teddytpc1** [comment]
Hi @GregWhiteyBialas.
Thanks for the changes. This PR will be merged after the `4.4.0` release.

**Comment by GregWhiteyBialas** [comment]
@teddytpc1 I have signed commit with gpg, can we merge it ?

**Comment by GregWhiteyBialas** [comment]
Hi @teddytpc1 Is there something that I can do to push this forward ?

**Comment by teddytpc1** [comment]
Changes have been tested with the Demo deployment. It worked fine.

**Comment by jonhattan** [comment]
This changes where merged on 4.4 branch and they're not present in master. Can you please move this changes into master?

**Pull request merged**
