### PR TITLE
fix typo in odfe security_actions.yml

### PR DESCRIPTION
**Pull request by dragospe**
I believe this may be a typo -- I'm quite new to the elastic stack, so forgive me if this is otherwise obvious!

### CODE REVIEW

**Comment by neonmei** [comment]
Hello @dragospe, good catch!

I believe those tasks in the block are stale/legacy. I did some quick grepping inside `roles/opendistro/opendistro-elasticsearch`, and could see that `elasticsearch_node_name` is used outside `security_actions.yml` and `kibana_node_name`/`filebeat_node_name` are just renamed to `od_node_name` as-is (basically just adding confusion or breaking things if `elasticsearch_node_name` and `filebeat_node_name` are defined at the same time and are not equal, because the `when` clauses don't guard that ouch).

I think the solution would be deleting the entire `block` with the `set_fact`  tasks and rename references of `od_node_name`  to `elasticsearch_node_name`. If you want to give it a try so github marks proper contribution, update the PR with the changes suggested. Otherwise I'll make the changes during the week :smile: 

Thank you for contributing!

**Review by neonmei — CHANGES_REQUESTED** [review]
I would delete this block

```yaml

- name: Configure node name
  block:
    - name: Setting node name (Elasticsearch)
      set_fact:
        od_node_name: "{{ elasticsearch_node_name }}"
      when:
        elasticsearch_node_name is defined and kibana_node_name is not defined
    - name: Setting node name (Kibana)
      set_fact:
        od_node_name: "{{ kibana_node_name }}"
      when:
        kibana_node_name is defined

    - name: Setting node name (Filebeat)
      set_fact:
        od_node_name: "{{ kibana_node_name }}"
        od_node_name: "{{ filebeat_node_name }}"
      when:
        filebeat_node_name is defined

```

And rename the `od_node_name` uses to `elasticsearch_node_name`. What do you think?

**Comment by dragospe** [comment]
Ah, thanks for taking a look! Most of my Wazuh'ing has been shooting the dark so far -- I'd trust you're judgement on the above. I've not used Wazuh in a few weeks, so my unfamiliarity with the elasticstack may become even more apparent if I try to make these changes myself :)

Thanks!

**Comment by neonmei** [comment]
No worries. I believe we should probably have something like a "good first issue" label to provide encouragement and platform for people to contribute and learn. Thanks again, and by all means feel free to open a PR, issue or message us on the slack channel or mailing lists if you see room for improvement.

I'll open a PR with these changes :+1:

**Pull request closed without merging**
