### PR TITLE
make agent registration delegate_to configurable

### PR DESCRIPTION
**Pull request by singuliere**
Registering to the API requires the port 55000 of the wazuh manager is
open. Depending on the firewall policy, it may be true from the
ansible controller, reason why both calls were delegated to localhost
in the original implementation at
6cb6d3bda84c65508881e293e3403dae94ff24cc

The role should be more flexible and allow for the API call to be made
on the host that has access to the port 55000 of the wazuh manager.

Fixes: https://github.com/wazuh/wazuh-ansible/issues/126

Signed-off-by: singuliere <singuliere@autistici.org>

### CODE REVIEW

**Comment by singuliere** [comment]
@paulcalabro @angystardust what do you think?

**Comment by paulcalabro** [comment]
Sweet! The logic looks good to me. I would probably put the variable next to the other API stuff under list of managers and name it `api_registrant`.  Something like this:

```
wazuh_managers:
  - address: 127.0.0.1
    port: 1514
    protocol: tcp
    api_port: 55000
    api_proto: 'http'
    api_user: null
    api_registrant: localhost
```

**Comment by angystardust** [comment]
Uhm...sorry but I don't think it's the right solution for what we're aiming to.
We should find a way to conditionally insert the _delegate_to_ parameter so that the task will run:
- with _delegate_to: localhost_ when we want agent registration from the ansible controller host
- without _delegate_to_ parameter at all, so the task will run on the host where the play is running on without the need to specify its name in the variable.

Some sample code just to help you understand what I mean:
```
wazuh_api_reachable_from_agents: False
```
```
delegate_to: "{{ 'localhost' if wazuh_api_reachable_from_agent is False else omit }}"
```

**Comment by angystardust** [comment]
I made some inline comments to your PR. Let me know what you think about it ;)

**Comment by paulcalabro** [comment]
@angystardust 

What are you thoughts on something like this:

```
delegate_to: "{{api_registrant|default('localhost') }}" 
```

This handles:

- delegating to a specified host, if specified
- running from the controller, if specified
- - running from the controller, if omitted

**Comment by paulcalabro** [comment]
@angystardust 

What are you thoughts on something like this:

```
delegate_to: "{{api_registrant|default('localhost') }}" 
```

This handles:

- delegating to a specified host; handles controller, agent, or another host (maybe you only want to open API access from one server-- the elastic stack server; not your controller and not hundreds of agents)
- running from the controller, if specified
- running from the controller, if omitted

**Comment by singuliere** [comment]
> I made some inline comments to your PR. Let me know what you think about it ;)

I'm grateful for the guidance and will amend the proposed change accordingly.

**Comment by singuliere** [comment]
The commit was amended and repushed with the suggested changes. Now running molecule tests [with this modification](https://lab.enough.community/singuliere/infrastructure/commit/a65504c2a2369888adce2add010205f5a7b0bf4f) in another context to verify it works (unless I'm mistaken there are no molecule tests for wazuh-ansible).

**Comment by paulcalabro** [comment]
I don't think so. I saw a `.kitchen` folder at one point, so that might have been used at one point.

**Comment by singuliere** [comment]
Unfortunately using **omit** fails because of [an existing ansible bug](https://github.com/ansible/ansible/issues/26009). Repushed an amended commit using **inventory_hostname** instead and running the molecule tests again.

**Comment by paulcalabro** [comment]
While we're changing this, could we move the:

```
      tags:
        - config
       - api
```

and `become` to the block level so it's DRY? :-)

**Comment by singuliere** [comment]
@paulcalabro moved the tags up to the block as suggested in this PR https://github.com/wazuh/wazuh-ansible/pull/133

**Comment by paulcalabro** [comment]
Very cool! Nice work!

**Comment by singuliere** [comment]
molecule tests passed on 3f93fa4

**Comment by singuliere** [comment]
Should this target the 3.7 branch or is master appropriate?

**Comment by singuliere** [comment]
@cadoming thanks for the update: the PR was retargeted to 3.7.

**Comment by angystardust** [comment]
> Unfortunately using **omit** fails because of [an existing ansible bug](https://github.com/ansible/ansible/issues/26009). Repushed an amended commit using **inventory_hostname** instead and running the molecule tests again.

Whoa...sorry I was unaware of "delegate_to + omit" the issue so I think that using _inventory_hostname_ is the right workaround :+1: 
My only claim is that the default value of `wazuh_api_reachable_from_agents: False` should really be _False_ for the security best-practice reasons I said in my previous comment https://github.com/wazuh/wazuh-ansible/issues/126#issuecomment-452439410

**Comment by singuliere** [comment]
@angystardust thanks for catching the inverted logic :sweat: fixed and repushed!

**Comment by singuliere** [comment]
ran molecule tests with the latest commit and ran into this error:

> ERROR! template error while templating string: no test named 'False'. String: {{ 'localhost' if wazuh_api_reachable_from_agent is False else inventory_hostname }}

Although it is valid python, it apparently is not valid jinja2. Reading the documentation to find out more.

**Comment by paulcalabro** [comment]
`False` should be lowercase.

**Comment by singuliere** [comment]
> False should be lowercase.

Not even :-)

> ERROR! template error while templating string: no test named 'false'. String: {{ 'localhost' if wazuh_api_reachable_from_agent is false else inventory_hostname }}

because none are among the [builtin jinja2 tests](http://jinja.pocoo.org/docs/2.10/templates/#list-of-builtin-tests)

However **not wazuh_api_reachable_from_agent** works as expected.

**Comment by singuliere** [comment]
I'm happy to say the last commit ( 7cce8e9) passes molecule tests.

**Comment by singuliere** [comment]
@paulcalabro indeed, [sameas](http://jinja.pocoo.org/docs/2.10/templates/#sameas) is the recommended way to compare with false. I have a slight preference for the **not** but I don't feel strongly either way.

**Comment by angystardust** [comment]
@jm404 can you please merge this? Every time I re-sync with this repo, I need to re-apply this patch manually :(

**Comment by angystardust** [comment]
@manuasir ping

**Comment by jm404** [comment]
Hi @angystardust @singuliere @paulcalabro ,

Sorry for the late response,

I checked the changed files and completely agree with the idea of delegating this to localhost when the Agent can't access port 55000. 

Maybe implementing a check to verify if the Agent can reach the Manager on 55000 would be a good idea also. We will explore solutions on this

PS: I'm changing the base of this from `3.7`to `develop` 

Best regards

Jose

**Comment by manuasir** [comment]
Hello @singuliere. Conflicts were resolved and this is being merged, thank you very much for contributing!

**Pull request merged**
