### PR TITLE
Fixes #93

### LINKED ISSUE #93: Wrong installation directory for Wazuh agent
Hi team,

The Ansible playbook for deploying a Wazuh agent is not installing it where the documentation currently [indicates](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-gui). According to the official documentation:
```
By default, all agent files will be found in: C:\Program Files(x86)\ossec-agent.
```

Instead, it's being installed in the root `C:/`.

Thanks

### PR DESCRIPTION
**Pull request by paulcalabro**
Updated the path to match this documentation:

```
By default, all agent files will be found in: C:\Program Files(x86)\ossec-agent.
```
(Source: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-gui)

### CODE REVIEW

**Comment by paulcalabro** [comment]
This will need to be tested on a Windows host.

**Comment by SitoRBJ** [comment]
Hello @paulcalabro,

Our colleague @cadoming is in the process of making this change. There are old systems that don not have the directory `Program Files(x86)` and we have to look at it. 

Thank you for your contribution.

Best regards, 

Alfonso Ruiz-Bravo

**Comment by paulcalabro** [comment]
Awesome! Yeah, I was a little unsure how reliable that directory location was.  I'm mostly a Mac and Linux user.

**Comment by cadoming** [comment]
Hi @paulcalabro,

Take a look at the PR #116 I just made, that PR solve the Issue #93 you refer here and also have some other changes. Thank for your time and your work.

Regards,
Carlos

**Comment by paulcalabro** [comment]
Looks good! I'll close this PR since the issue has been resolved.

**Pull request closed without merging**
