### PR TITLE
Refactored the default variables file

### PR DESCRIPTION
**Pull request by paulcalabro**
1. Split the default variables into two files -- one for Wazuh Manager variables and one for Wazuh Agent variables
    2. Set the wazuh_manager_fqdn and node_name variables to the hostname of the instance
    3. Sorted hash keys to make finding keys easier

### CODE REVIEW

**Comment by cadoming** [comment]
Hi @paulcalabro,

Thank you very much for the time and effort spent on improving the code. We liked the idea of splitting the `default/main.yml` file to make it easier to find the variables, unfortunately this option is only available from version 2.6 of ansible so all users who have a previous version couldn't use this code. We are studying the possibility of creating a branch with this modification.

In addition to testing your code gave me error in the installation due to missing some variables such as `mail_maxperhour `or `mail_queue_size`.

Regarding the modification of variables such as `cluster.node_name: "{{ ansible_hostname }}"` and `wazuh_manager_fqdn: "{{ ansible_hostname }}"` we think this is a good idea.

regards,
Carlos

**Comment by paulcalabro** [comment]
Hi @cadoming,

You're welcome. In regards to the Ansible version, which Ansible versions do you guys officially support? 

Not sure about those variables you mentioned. Either I missed them somehow or maybe there was added in a previous commit and I forgot to pull. Thanks for catching that. I'll add those. 

Glad the modification of variables containing the hostname is useful.

Cheers,
Paul

**Comment by cadoming** [comment]
Hi @paulcalabro,

We support version 2.5, that is the oldest version that ansible support. (https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html)

Regards,
Carlos

**Comment by paulcalabro** [comment]
I'll close this for now since this feature won't be possible at this time.

**Pull request closed without merging**
